version: '3.8' # if no version is specificed then v1 is assumed. Recommend v2 minimum

services:
  ubuntu-c:
    hostname: ubuntu-c
    container_name: ubuntu-c
    image: arunstiwari/ansible:ansible
    ports:
      - ${UBUNTUC_PORT_SSHD}:22
      - ${UBUNTUC_PORT_TTYD}:7681
    privileged: true
    volumes:
      - ${CONFIG}:/config
      - ${ANSIBLE_HOME}/shared:/shared
      - ${ANSIBLE_HOME}/ubuntu-c/ansible:/home/ansible
      - ${ANSIBLE_HOME}/ubuntu-c/root:/root
    networks:
      - tekmentors.io

  ubuntu1:
    hostname: ubuntu1
    container_name: ubuntu1
    image: arunstiwari/ansible:ubuntu
    ports:
      - ${UBUNTU1_PORT_SSHD}:22
      - ${UBUNTU1_PORT_TTYD}:7681
    privileged: true
    volumes:
      - ${CONFIG}:/config
      - ${ANSIBLE_HOME}/shared:/shared
      - ${ANSIBLE_HOME}/ubuntu1/ansible:/home/ansible
      - ${ANSIBLE_HOME}/ubuntu1/root:/root
    networks:
      - tekmentors.io

  ubuntu2:
    hostname: ubuntu2
    container_name: ubuntu2
    image: arunstiwari/ansible:ubuntu
    ports:
      - ${UBUNTU2_PORT_SSHD}:22
      - ${UBUNTU2_PORT_TTYD}:7681
    privileged: true
    volumes:
      - ${CONFIG}:/config
      - ${ANSIBLE_HOME}/shared:/shared
      - ${ANSIBLE_HOME}/ubuntu2/ansible:/home/ansible
      - ${ANSIBLE_HOME}/ubuntu2/root:/root
    networks:
      - tekmentors.io

  ubuntu3:
    hostname: ubuntu3
    container_name: ubuntu3
    image: arunstiwari/ansible:ubuntu
    ports:
      - ${UBUNTU3_PORT_SSHD}:22
      - ${UBUNTU3_PORT_TTYD}:7681
    privileged: true
    volumes:
      - ${CONFIG}:/config
      - ${ANSIBLE_HOME}/shared:/shared
      - ${ANSIBLE_HOME}/ubuntu3/ansible:/home/ansible
      - ${ANSIBLE_HOME}/ubuntu3/root:/root
    networks:
      - tekmentors.io

  centos1:
    hostname: centos1
    container_name: centos1
    image: arunstiwari/ansible:centos
    #image: arunstiwari/ansible:centos-sshd-2222
    ports:
      - ${CENTOS1_PORT_SSHD}:22
      #- ${CENTOS1_PORT_SSHD}:2222
      - ${CENTOS1_PORT_TTYD}:7681
    privileged: true
    volumes:
      - ${CONFIG}:/config
      - ${ANSIBLE_HOME}/shared:/shared
      - ${ANSIBLE_HOME}/centos1/ansible:/home/ansible
      - ${ANSIBLE_HOME}/centos1/root:/root
    networks:
      - tekmentors.io

  centos2:
    hostname: centos2
    container_name: centos2
    image: arunstiwari/ansible:centos
    ports:
      - ${CENTOS2_PORT_SSHD}:22
      - ${CENTOS2_PORT_TTYD}:7681
    privileged: true
    volumes:
      - ${CONFIG}:/config
      - ${ANSIBLE_HOME}/shared:/shared
      - ${ANSIBLE_HOME}/centos2/ansible:/home/ansible
      - ${ANSIBLE_HOME}/centos2/root:/root
    networks:
      - tekmentors.io

  centos3:
    hostname: centos3
    container_name: centos3
    image: arunstiwari/ansible:centos
    ports:
      - ${CENTOS3_PORT_SSHD}:22
      - ${CENTOS3_PORT_TTYD}:7681
    privileged: true
    volumes:
      - ${CONFIG}:/config
      - ${ANSIBLE_HOME}/shared:/shared
      - ${ANSIBLE_HOME}/centos3/ansible:/home/ansible
      - ${ANSIBLE_HOME}/centos3/root:/root
    networks:
      - tekmentors.io

networks:
  tekmentors.io:
    name: tekmentors.io